services:
  dom-shield-demo:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: dom-shield-demo
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.dom-shield.description=DOM Shield Demo Application"
      - "com.dom-shield.version=1.0.0"
